on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: View the information of the pusher
      run: |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"


    - name: View the github context
      run: echo "$GITHUB_CONTEXT"
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}